name: Collect Scorecard Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths:
      - 'backend/**'
      - ".github/workflows/collect-scorecard-data.yml"
  pull_request:
    paths:
      - 'backend/**'
      - ".github/workflows/collect-scorecard-data.yml"

jobs:
  CollectScorecardData:
    runs-on: ubuntu-latest

    steps:
      # Check out codebasehow 
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Configure and install Chrome
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Configure ChromeDriver
      - name: Set up ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          chromedriver --version

      # Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run data collection script
      - name: Run Data Collection Script
        env:
          blob_account_connection_string: ${{ secrets.blob_account_connection_string }}
          golf_course_name: ${{ secrets.golf_course_name }}
          round_site_base_url: ${{ vars.round_site_base_url }}
          round_site_username: ${{ secrets.round_site_username }}
          round_site_password: ${{ secrets.round_site_password }}
        run: |
          python -m backend.collect_scorecard_data  